version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongo-network
    command: ["mongod", "--auth"]

networks:
  mongo-network:
    driver: bridge

volumes:
  mongodb-data:
